apiVersion: v1
kind: PersistentVolume
metadata:
  name: hive-nfs-test1
  namespace: metering
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany
  nfs:
    path: /var/export1/nfs
    server: 9.152.85.221
