apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metering-nfs
  namespace: metering
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
