apiVersion: metering.openshift.io/v1
kind: Report
metadata:
  name: node-cpu-allocatable-raw
spec:
  reportingStart: '2020-09-11T00:00:00Z'
  reportingEnd: '2020-09-11T23:00:00Z'
  query: "node-cpu-allocatable-raw"
  runImmediately: true
